### ISSUE TITLE
[browser-kit] During initialization, `www-client/brave-bin-1.68.141` encounters an error and exits.

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#94] opened 2024-08-22 19:29 UTC
```
$ eix brave-bin
[I] www-client/brave-bin [1]
     Available versions:  1.68.141 {gnome-keyring KERNEL="linux" L10N="+am +ar +bg +bn +ca +cs +da +de +el +en-GB +en-US +es +es-419 +et +fa +fi +fil +fr +gu +he +hi +hr +hu +id +it +ja +kn +ko +lt +lv +ml +mr +ms +nb +nl +pl +pt-BR +pt-PT +ro +ru +sk +sl +sr +sv +sw +ta +te +th +tr +uk +vi +zh-CN +zh-TW"}
     Installed versions:  1.68.141(15:24:08 22/08/24)(-gnome-keyring KERNEL="linux" L10N="en-US -am -ar -bg -bn -ca -cs -da -de -el -en-GB -es -es-419 -et -fa -fi -fil -fr -gu -he -hi -hr -hu -id -it -ja -kn -ko -lt -lv -ml -mr -ms -nb -nl -pl -pt-BR -pt-PT -ro -ru -sk -sl -sr -sv -sw -ta -te -th -tr -uk -vi -zh-CN -zh-TW")
     Homepage:            https://brave.com
     Description:         Brave Web Browser

[1] "browser-kit" /var/git/meta-repo/kits/browser-kit

$ brave-bin 
[18548:18611:0822/152704.091606:ERROR:file_path_watcher_inotify.cc(337)] inotify_init() failed: Too many open files (24)
[18548:18548:0822/152704.641504:ERROR:proxy_config_service_linux.cc(626)] inotify_init failed: Too many open files (24)
[18679:18683:0822/152704.757340:ERROR:file_path_watcher_inotify.cc(337)] inotify_init() failed: Too many open files (24)
[18548:18548:0822/152705.558759:FATAL:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[0822/152705.594651:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0822/152705.595101:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0822/152705.595271:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0822/152705.596959:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0822/152705.599874:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0822/152705.600273:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0822/152705.611545:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0822/152705.611743:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0822/152705.614988:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0822/152705.615239:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Trace/breakpoint trap
```

**Comment by cuantar** [comment] 2024-08-22 19:34
Note that the `inotify` messages are unrelated to the real problem, and occur before a dialog appears asking me to approve password wallet access for `brave-bin`.  Upon my affirmative selection, the remaining messages in the output above about `elf_dynamic_array_reader.h` are printed and the program exits.

**Comment by geaaru** [comment] 2024-08-22 20:03
:thinking: it seems issues related to the use of 3D.
Take a look [here](https://www.macaronios.org/blog/phoenix-23.11/). I implemented the `macaronictl browser` command to setup browser options (WIP) because I see a lot of issues.
Can you try to run `brave-bin --disable-gpu --disable-software-rasterizer`?

**Comment by cuantar** [comment] 2024-08-22 20:27
I had not, until now, because `brave-bin --help` returns only `No manual entry for brave-bin` instead of any substance.

The behavior with the suggested options is unchanged.

**Comment by cuantar** [comment] 2024-08-22 20:29
It's not very high-priority _for me personally_ anymore, because I only used `brave-bin` when forced to use MS Teams to communicate with people; when Brave wouldn't start this time, I tried Firefox and it worked.  Apparently something has changed somewhat recently, because just a few weeks ago, Teams in Firefox couldn't see my microphone.

**Comment by cuantar** [comment] 2024-08-22 20:32
Also, it's probably worth noting that I've observed the problem on two different machines.  One has a discrete nVidia GPU and uses the proprietary driver.  The other has an Intel onboard GPU.

**Comment by geaaru** [comment] 2024-08-22 20:41
Interesting, i have an issue with Firefox and my webcam with the last versions. It's weird. Yeah, we need investigate on this issue. I think that could be shared.

**Comment by geaaru** [comment] 2024-08-23 12:31
This could be a workaround with an old version:
```
$> emerge --unmerge brave-bin
$> emerge anise
$> anise repo update
$> anise i repository/macaroni-phoenix
$> anise repo update && anise i brave-bin --nodeps
```
Let me know if this confirm that an old version it works better ;)

**Comment by geaaru** [comment] 2024-09-03 05:26
In `macaroni-phoenix-testing` I now have the `brave-bin-1.68.137` version, which starts correctly. Let me know ;)

**Comment by geaaru** [comment] 2024-09-25 09:55
![image](https://github.com/user-attachments/assets/1e30774a-158f-4dd0-b0f0-cdc0232532be)

No issues with 1.69.168, too.
Closing this issue. You reopen it if you still have issues but I think that the problem is not related to the browser.

**Closed as completed by geaaru** 2024-09-25 09:55 UTC
Labels: bug
