### ISSUE TITLE
[core-kit] add app-admin/anise-portage-converter to MARK's tree

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#24] opened 2024-08-03 09:58 UTC
Having it in one of the MARK kits will make the migration even easier.

**Comment by geaaru** [comment] 2024-08-03 17:17
Closing this as a duplicate of #5 
Sorry, typo. I wrote `anise-portage-sync` instead of `anise-portage-converter`

**Closed as completed by geaaru** 2024-08-03 17:17 UTC
Labels: enhancement, good first issue, MARK
